language: ruby
rvm:
  - 1.9.2
env:
  - DB=mysql GOVUK_APP_DOMAIN=test.gov.uk RUBYOPT="-rpsych"
services:
  - elasticsearch
before_install:
- sudo add-apt-repository ppa:gds/govuk
- sudo apt-get update -qq
- sudo apt-get install -qq aspell aspell-en libaspell-dev
- sudo apt-get install -qq -v 0.20.6-ppa1~lucid1 elasticsearch
script:
  - bundle exec rake
bundler_args: --without=development
branches:
  except:
    - release
notifications:
  email: false
